title: Nheljim Edis
description: Proactive and dedicated in everything
theme: minima
author: nheljim21
email: edisheljim21@gmail.com
github_username: nheljim21

# Navigation links
nav:
  - Home: /
  - Projects: Short Composition- Reflective Essay
  - Contact: edisnheljim21@gmail.com

  # Social Links
social_links:
  - title: GitHub
    url: "https://github.com/nheljim21"
  - title: LinkedIn
    url: "https://www.linkedin.com/in/nheljim-edis-42075721b/
