site_name: Nheljim Mantawil Edis
site_description: Proactive and dedicated in everything
site_author: nheljim21
theme:
  name: material
  palette:
    primary: indigo
    accent: amber

nav:
  - Home: index.md
  - Projects: projects.md
  - About: about.md
  - Contact: contact.md

repo_url: https://github.com/nheljim21/portfolio
repo_name: GitHub

# Plugins
plugins:
  - search
  - mkdocs-material

# Extra settings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nheljim21
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nheljim-edis-42075721b/
